version: '2'
services:
  api:
    build: ./api
    command: yarn start
    volumes:
      - ./api:/home/node
    environment:
      - PORT=8000
  nginx:
    image: nginx
    working_dir: /etc/nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
